# Control plane provider
{{- if .Values.controlPlane }}
{{- range $controlPlane := .Values.controlPlane }}
  {{- $controlPlaneNamespace := default ( printf "%s-%s" $controlPlane.name "control-plane-system" ) $controlPlane.namespace }}
  {{- $controlPlaneName := $controlPlane.name }}
  {{- $controlPlaneVersion := $controlPlane.version }}
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "1"
  name: {{ $controlPlaneNamespace }}
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: ControlPlaneProvider
metadata:
  name: {{ $controlPlaneName }}
  namespace: {{ $controlPlaneNamespace }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "2"
{{- if or $controlPlaneVersion $.Values.configSecret.name }}
spec:
{{- end}}
{{- if $controlPlaneVersion }}
  version: {{ $controlPlaneVersion }}
{{- end }}
{{- if $.Values.configSecret.name }}
  configSecret:
    name: {{ $.Values.configSecret.name }}
    {{- if $.Values.configSecret.namespace }}
    namespace: {{ $.Values.configSecret.namespace }}
    {{- end }}
{{- end }}
{{- if $controlPlane.manifestPatches }}
  manifestPatches: {{ toYaml $controlPlane.manifestPatches | nindent 4 }}
{{- end }}
{{- end }} {{/* range $controlPlane := .Values.controlPlane */}}
{{- end }} {{/* if .Values.controlPlane */}}
