# Core provider
{{- if .Values.core }}
  {{- $coreNamespace := default ( printf "%s-%s" .Values.core.name "capi-system" ) .Values.core.namespace }}
  {{- $coreName := .Values.core.name }}
  {{- $coreVersion := .Values.core.version }}
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "1"
  name: {{ $coreNamespace }}
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: CoreProvider
metadata:
  name: {{ $coreName }}
  namespace: {{ $coreNamespace }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "2"
    "argocd.argoproj.io/sync-wave": "2"
{{- if or $coreVersion $.Values.configSecret.name }}
spec:
{{- end}}
{{- if $coreVersion }}
  version: {{ $coreVersion }}
{{- end }}
{{- if $.Values.manager }}
  manager:
{{- if and $.Values.manager.featureGates $.Values.manager.featureGates.core }}
    featureGates:
    {{- range $key, $value := $.Values.manager.featureGates.core }}
      {{ $key }}: {{ $value }}
    {{- end }}
{{- end }}
{{- end }}
{{- if $.Values.configSecret.name }}
  configSecret:
    name: {{ $.Values.configSecret.name }}
    {{- if $.Values.configSecret.namespace }}
    namespace: {{ $.Values.configSecret.namespace }}
    {{- end }}
{{- end }}
{{- if .Values.core.manifestPatches }}
  manifestPatches: {{ toYaml .Values.core.manifestPatches | nindent 4 }}
{{- end }}
{{- if .Values.core.additionalManifests }}
  additionalManifests:
    name: {{ .Values.core.additionalManifests.name }}
    {{- if .Values.core.additionalManifests.namespace }}
    namespace: {{ .Values.core.additionalManifests.namespace }}
    {{- end }} {{/* if .Values.core.additionalManifests.namespace */}}
{{- end }}
{{- if .Values.core.additionalManifests }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.core.additionalManifests.name }}
  namespace: {{ default .Values.coreNamespace .Values.core.additionalManifests.namespace }}
data:
  manifests: {{- toYaml .Values.core.additionalManifests.manifests | nindent 4 }}
{{- end }}
{{- end }} {{/* if .Values.core */}}
